/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author smoreno
 */
public class ActRepo extends javax.swing.JDialog {

    /**
     * Creates new form ActRepo
     */
    public ActRepo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelAggUsuario = new javax.swing.JPanel();
        jButtonConfAggUsr = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();
        jSpinnerAnios = new javax.swing.JSpinner();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelAggRelac = new javax.swing.JPanel();
        jButtonConfAggRel = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRelacion2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListRelacion1 = new javax.swing.JList<>();
        jSpinnerAniosRel = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAggUsr = new javax.swing.JButton();
        jButtonAggRelac = new javax.swing.JButton();
        jButtonDelUsr = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelAggUsuario.setBackground(new java.awt.Color(0, 255, 204));
        jPanelAggUsuario.setVisible(false);

        jButtonConfAggUsr.setText("Aceptar");
        jButtonConfAggUsr.setEnabled(false);
        jButtonConfAggUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfAggUsrActionPerformed(evt);
            }
        });

        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jListUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListUsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListUsuarios);

        jSpinnerAnios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAniosStateChanged(evt);
            }
        });
        jSpinnerAnios.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinnerAniosPropertyChange(evt);
            }
        });

        jTextFieldNombreUsuario.setText("jTextField1");
        jTextFieldNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreUsuarioFocusLost(evt);
            }
        });

        jLabel2.setText("Nombre usuario");

        jLabel3.setText("Relacionado con:");

        jLabel4.setText("Años de relacion");

        javax.swing.GroupLayout jPanelAggUsuarioLayout = new javax.swing.GroupLayout(jPanelAggUsuario);
        jPanelAggUsuario.setLayout(jPanelAggUsuarioLayout);
        jPanelAggUsuarioLayout.setHorizontalGroup(
            jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jSpinnerAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonConfAggUsr, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35))
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelAggUsuarioLayout.setVerticalGroup(
            jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonConfAggUsr)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAggUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAggUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAggUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanelAggRelac.setBackground(new java.awt.Color(255, 153, 51));
        jPanelAggRelac.setVisible(false);

        jButtonConfAggRel.setText("Aceptar");
        jButtonConfAggRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfAggRelActionPerformed(evt);
            }
        });
        jButtonConfAggRel.setEnabled(false);

        jButton8.setText("Cerrar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jListRelacion2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListRelacion2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListRelacion2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListRelacion2);

        jListRelacion1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListRelacion1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListRelacion1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListRelacion1);

        jSpinnerAniosRel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAniosRelStateChanged(evt);
            }
        });

        jLabel5.setText("Usuario");

        jLabel6.setText("Relacion Con:");

        jLabel7.setText("Años de relacion");

        javax.swing.GroupLayout jPanelAggRelacLayout = new javax.swing.GroupLayout(jPanelAggRelac);
        jPanelAggRelac.setLayout(jPanelAggRelacLayout);
        jPanelAggRelacLayout.setHorizontalGroup(
            jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jSpinnerAniosRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(jButtonConfAggRel)))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanelAggRelacLayout.setVerticalGroup(
            jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfAggRel)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addComponent(jSpinnerAniosRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAggRelacLayout.createSequentialGroup()
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        jButton9.setText("jButton9");

        jButton10.setText("jButton10");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton9))
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel1.setText("Que deseas editar ?");

        jButtonAggUsr.setText("Agregar Usuario");
        jButtonAggUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAggUsrActionPerformed(evt);
            }
        });

        jButtonAggRelac.setText("Agregar relacion");
        jButtonAggRelac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAggRelacActionPerformed(evt);
            }
        });

        jButtonDelUsr.setText("Eliminar Usuario");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAggUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAggRelac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonAggUsr)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonAggRelac)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonDelUsr)
                        .addGap(69, 69, 69)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanelAggUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAggRelac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAggUsr)
                    .addComponent(jButtonAggRelac)
                    .addComponent(jButtonDelUsr)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAggUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAggUsrActionPerformed
        // TODO add your handling code here:
        
        jButtonAggRelac.setEnabled(false);
        jButtonAggUsr.setEnabled(false);
        jButtonDelUsr.setEnabled(false);
        Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();
        modelo = new DefaultListModel();
        this.idMax = 0;
        while(usuario!=null){
            System.out.println(usuario.getValor().getUsuario());
            modelo.addElement(usuario.getValor().getUsuario());
            if(usuario.getValor().getId()>this.idMax)this.idMax=usuario.getValor().getId();
            usuario=usuario.getSiguiente();
        }
        jListUsuarios.setModel(modelo);
        jPanelAggUsuario.setVisible(true);    

    }//GEN-LAST:event_jButtonAggUsrActionPerformed

    private void jButtonConfAggUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfAggUsrActionPerformed
        // TODO add your handling code here:
        String nmUsuario = jTextFieldNombreUsuario.getText();
        Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();
        Usuario nuevoUsuario = new Usuario();
        this.idMax = this.idMax+1;
        nuevoUsuario.setId(this.idMax);
        nuevoUsuario.setUsuario(nmUsuario);
        System.out.println("---->" + nuevoUsuario.getId());
        int idRelacion = 0;
        while(usuario!=null){
            if(usuario.getValor().getUsuario().equals(jListUsuarios.getSelectedValue())){
                idRelacion = usuario.getValor().getId();
                break;
            }
            usuario = usuario.getSiguiente();
        }

        Arista relacion = new Arista(nuevoUsuario.getId(),idRelacion,(Integer)jSpinnerAnios.getValue());

        Main.repo.getAristaList().agregarAlFinal(relacion);
        Main.repo.getUsuariosList().agregarAlFinal(nuevoUsuario);
        JOptionPane.showMessageDialog(this, "Usuario agregado correctamente");
        usuario = Main.repo.getUsuariosList().getPrimero();
        modelo = new DefaultListModel();
        while(usuario!=null){
            System.out.println(usuario.getValor().getUsuario());
            modelo.addElement(usuario.getValor().getUsuario());
            usuario=usuario.getSiguiente();
        }
        jListUsuarios.setModel(modelo);

//        usuario = Main.repo.getUsuariosList().getPrimero();
//        while(usuario!=null){
//            System.out.println(usuario.getValor().getUsuario());
//            usuario=usuario.getSiguiente();
//        }
    }//GEN-LAST:event_jButtonConfAggUsrActionPerformed

    private void jTextFieldNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioFocusLost
        // TODO add your handling code here:
        if(jTextFieldNombreUsuario.getText()!=null ){
            if (!jTextFieldNombreUsuario.getText().isBlank() || !jTextFieldNombreUsuario.getText().isEmpty()){
                if(jListUsuarios.getSelectedValue()!=null && (Integer)jSpinnerAnios.getValue() != 0){
                    jButtonConfAggUsr.setEnabled(true);
                }else{
                            jButtonConfAggUsr.setEnabled(false);
                        }                
            }else{
                        jButtonConfAggUsr.setEnabled(false);
                    }
        }else{
                    jButtonConfAggUsr.setEnabled(false);
                }

    }//GEN-LAST:event_jTextFieldNombreUsuarioFocusLost

    private void jListUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListUsuariosValueChanged
        // TODO add your handling code here:
                if(jTextFieldNombreUsuario.getText()!=null ){
                    if (!jTextFieldNombreUsuario.getText().isBlank() || !jTextFieldNombreUsuario.getText().isEmpty()){
                        if(jListUsuarios.getSelectedValue()!=null && (Integer)jSpinnerAnios.getValue() != 0){
                            jButtonConfAggUsr.setEnabled(true);
                        }else{
                            jButtonConfAggUsr.setEnabled(false);
                        }                
            }else{
                        jButtonConfAggUsr.setEnabled(false);
                    }
        }else{
                    jButtonConfAggUsr.setEnabled(false);
                }
    }//GEN-LAST:event_jListUsuariosValueChanged

    private void jSpinnerAniosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinnerAniosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerAniosPropertyChange

    private void jSpinnerAniosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAniosStateChanged
        // TODO add your handling code here:
                        if(jTextFieldNombreUsuario.getText()!=null ){
                    if (!jTextFieldNombreUsuario.getText().isBlank() || !jTextFieldNombreUsuario.getText().isEmpty()){
                        if(jListUsuarios.getSelectedValue()!=null && (Integer)jSpinnerAnios.getValue() != 0){
                            jButtonConfAggUsr.setEnabled(true);
                        }else{
                            jButtonConfAggUsr.setEnabled(false);
                        }                
            }else{
                        jButtonConfAggUsr.setEnabled(false);
                    }
        }else{
                    jButtonConfAggUsr.setEnabled(false);
                }
    }//GEN-LAST:event_jSpinnerAniosStateChanged

    private void jButtonConfAggRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfAggRelActionPerformed
        // TODO add your handling code here:
        Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();

        int idRelacionUsu1 = 0;
        int idRelacionUsu2 = 0;
        while(usuario!=null){
            if(usuario.getValor().getUsuario().equals(jListRelacion1.getSelectedValue())){
                idRelacionUsu1 = usuario.getValor().getId();
            }else if (usuario.getValor().getUsuario().equals(jListRelacion2.getSelectedValue())){
                idRelacionUsu2 = usuario.getValor().getId();
            }
            usuario = usuario.getSiguiente();
        }
        
        Arista relacion = new Arista(idRelacionUsu1,idRelacionUsu2,(Integer)jSpinnerAniosRel.getValue());

        Main.repo.getAristaList().agregarAlFinal(relacion);
        JOptionPane.showMessageDialog(this, "Relacion creada");
//        Nodo<Arista>arista = Main.repo.getAristaList().getPrimero();
//        while(arista!=null){
//            System.out.println("Origen-> "+arista.getValor().getOrigen()+ "; Destino-> "+arista.getValor().getDestino()+ ";Anios-> "+arista.getValor().getYears());
//            arista=arista.getSiguiente();
//        }
    }//GEN-LAST:event_jButtonConfAggRelActionPerformed

    private void jListRelacion1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListRelacion1ValueChanged
        // TODO add your handling code here:
         if(jListRelacion1.getSelectedValue()!=null && jListRelacion2.getSelectedValue()!=null && (Integer)jSpinnerAniosRel.getValue() != 0){
                            jButtonConfAggRel.setEnabled(true);
        }else{
            jButtonConfAggRel.setEnabled(false);
        } 
    }//GEN-LAST:event_jListRelacion1ValueChanged

    private void jButtonAggRelacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAggRelacActionPerformed
        // TODO add your handling code here:
        jButtonAggRelac.setEnabled(false);
        jButtonAggUsr.setEnabled(false);
        jButtonDelUsr.setEnabled(false);
        if(modelo==null){
            Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();
            modelo = new DefaultListModel();
            this.idMax = 0;
            while(usuario!=null){
                System.out.println(usuario.getValor().getUsuario());
                modelo.addElement(usuario.getValor().getUsuario());
                if(usuario.getValor().getId()>this.idMax)this.idMax=usuario.getValor().getId();
                usuario=usuario.getSiguiente();
            }
        }
        
        jListRelacion1.setModel(modelo);
        jListRelacion2.setModel(modelo);
        jPanelAggRelac.setVisible(true);
    }//GEN-LAST:event_jButtonAggRelacActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanelAggUsuario.setVisible(false);
        jButtonAggRelac.setEnabled(true);
        jButtonAggUsr.setEnabled(true);
        jButtonDelUsr.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jListRelacion2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListRelacion2ValueChanged
        // TODO add your handling code here:
        
        if(jListRelacion1.getSelectedValue()!=null && jListRelacion2.getSelectedValue()!=null && (Integer)jSpinnerAniosRel.getValue() != 0){
                            jButtonConfAggRel.setEnabled(true);
        }else{
            jButtonConfAggRel.setEnabled(false);
        } 
    }//GEN-LAST:event_jListRelacion2ValueChanged

    private void jSpinnerAniosRelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAniosRelStateChanged
        // TODO add your handling code here:
        
        if(jListRelacion1.getSelectedValue()!=null && jListRelacion2.getSelectedValue()!=null && (Integer)jSpinnerAniosRel.getValue() != 0){
                            jButtonConfAggRel.setEnabled(true);
        }else{
            jButtonConfAggRel.setEnabled(false);
        } 
    }//GEN-LAST:event_jSpinnerAniosRelStateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jPanelAggRelac.setVisible(false);
        jButtonAggRelac.setEnabled(true);
        jButtonAggUsr.setEnabled(true);
        jButtonDelUsr.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActRepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActRepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActRepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActRepo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActRepo dialog = new ActRepo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    private int idMax;
    private DefaultListModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAggRelac;
    private javax.swing.JButton jButtonAggUsr;
    private javax.swing.JButton jButtonConfAggRel;
    private javax.swing.JButton jButtonConfAggUsr;
    private javax.swing.JButton jButtonDelUsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jListRelacion1;
    private javax.swing.JList<String> jListRelacion2;
    private javax.swing.JList<String> jListUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAggRelac;
    private javax.swing.JPanel jPanelAggUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerAnios;
    private javax.swing.JSpinner jSpinnerAniosRel;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
