/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author smoreno
 */
public class ActualizarRepo2 extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public ActualizarRepo2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAggUsr = new javax.swing.JButton();
        jButtonDelUsr = new javax.swing.JButton();
        jButtonAggRelac = new javax.swing.JButton();
        jPanelAggUsuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jSpinnerAnios = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();
        jButtonConfAggUsr = new javax.swing.JButton();
        jButtonCerrarAggUsr = new javax.swing.JButton();
        jPanelAggRelac = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRelacion1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListRelacion2 = new javax.swing.JList<>();
        jSpinnerAniosRel = new javax.swing.JSpinner();
        jButtonConfAggRel = new javax.swing.JButton();
        jButtonCerrarAggRelac = new javax.swing.JButton();
        jPanelDelUsr = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListDelUsr = new javax.swing.JList<>();
        jButtonConfDelUsr = new javax.swing.JButton();
        jButtonCerrarEliUsr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Que deseas actualizar ?");

        jButtonAggUsr.setText("Agregar Usuario");
        jButtonAggUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAggUsrActionPerformed(evt);
            }
        });

        jButtonDelUsr.setText("Eliminar Usuario");
        jButtonDelUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelUsrActionPerformed(evt);
            }
        });

        jButtonAggRelac.setText("Agregar relacion");
        jButtonAggRelac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAggRelacActionPerformed(evt);
            }
        });

        jPanelAggUsuario.setBackground(new java.awt.Color(255, 153, 153));
        jPanelAggUsuario.setVisible(false);

        jLabel3.setText("Nombre de Usuario");

        jLabel4.setText("Relacion con: ");

        jLabel5.setText("Años de relacion");

        jTextFieldNombreUsuario.setToolTipText("s");
        jTextFieldNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreUsuarioFocusLost(evt);
            }
        });

        jSpinnerAnios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAniosStateChanged(evt);
            }
        });
        jSpinnerAnios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinnerAniosFocusLost(evt);
            }
        });

        jListUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListUsuarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jListUsuariosFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jListUsuarios);

        jButtonConfAggUsr.setText("Aceptar");
        jButtonConfAggUsr.setEnabled(false);
        jButtonConfAggUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfAggUsrActionPerformed(evt);
            }
        });

        jButtonCerrarAggUsr.setText("Cerrar");
        jButtonCerrarAggUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarAggUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAggUsuarioLayout = new javax.swing.GroupLayout(jPanelAggUsuario);
        jPanelAggUsuario.setLayout(jPanelAggUsuarioLayout);
        jPanelAggUsuarioLayout.setHorizontalGroup(
            jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAggUsuarioLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)))
                .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(85, 85, 85))
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jSpinnerAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAggUsuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonConfAggUsr)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarAggUsr)
                        .addGap(33, 33, 33))))
        );
        jPanelAggUsuarioLayout.setVerticalGroup(
            jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAggUsuarioLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jSpinnerAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAggUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonConfAggUsr)
                            .addComponent(jButtonCerrarAggUsr))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanelAggRelac.setBackground(new java.awt.Color(0, 204, 204));
        jPanelAggRelac.setVisible(false);

        jLabel1.setText("Seleccione usuario");

        jLabel6.setText("Relacionado con:");

        jLabel7.setText("Años de relacion");

        jListRelacion1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListRelacion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jListRelacion1FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jListRelacion1);

        jListRelacion2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListRelacion2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jListRelacion2FocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jListRelacion2);

        jSpinnerAniosRel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAniosRelStateChanged(evt);
            }
        });

        jButtonConfAggRel.setText("Aceptar");
        jButtonConfAggRel.setEnabled(false);
        jButtonConfAggRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfAggRelActionPerformed(evt);
            }
        });

        jButtonCerrarAggRelac.setText("Cerrar");
        jButtonCerrarAggRelac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarAggRelacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAggRelacLayout = new javax.swing.GroupLayout(jPanelAggRelac);
        jPanelAggRelac.setLayout(jPanelAggRelacLayout);
        jPanelAggRelacLayout.setHorizontalGroup(
            jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7))
                    .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerAniosRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                                .addComponent(jButtonConfAggRel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCerrarAggRelac)))))
                .addGap(29, 29, 29))
        );
        jPanelAggRelacLayout.setVerticalGroup(
            jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanelAggRelacLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSpinnerAniosRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanelAggRelacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonConfAggRel)
                            .addComponent(jButtonCerrarAggRelac))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelDelUsr.setBackground(new java.awt.Color(255, 0, 51));
        jPanelDelUsr.setVisible(false);

        jLabel8.setText("Usuario a eliminar");

        jListDelUsr.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListDelUsr);

        jButtonConfDelUsr.setText("Eliminar");
        setEnabled(false);
        jButtonConfDelUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfDelUsrActionPerformed(evt);
            }
        });

        jButtonCerrarEliUsr.setText("Cerrar");
        jButtonCerrarEliUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarEliUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDelUsrLayout = new javax.swing.GroupLayout(jPanelDelUsr);
        jPanelDelUsr.setLayout(jPanelDelUsrLayout);
        jPanelDelUsrLayout.setHorizontalGroup(
            jPanelDelUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDelUsrLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(jPanelDelUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDelUsrLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanelDelUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConfDelUsr)
                            .addComponent(jButtonCerrarEliUsr)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDelUsrLayout.setVerticalGroup(
            jPanelDelUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDelUsrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(jPanelDelUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDelUsrLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDelUsrLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonConfDelUsr)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCerrarEliUsr)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonAggUsr)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAggRelac)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonDelUsr))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAggUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAggRelac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDelUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAggUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAggRelac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDelUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAggRelac)
                    .addComponent(jButtonDelUsr)
                    .addComponent(jButtonAggUsr))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAggUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAggUsrActionPerformed

        jButtonAggRelac.setEnabled(false);
        jButtonAggUsr.setEnabled(false);
        jButtonDelUsr.setEnabled(false);
        Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();
        modelo = new DefaultListModel();
        this.idMax = 0;
        while(usuario!=null){
            System.out.println(usuario.getValor().getUsuario());
            modelo.addElement(usuario.getValor().getUsuario());
            if(usuario.getValor().getId()>this.idMax)this.idMax=usuario.getValor().getId();
            usuario=usuario.getSiguiente();
        }
        jListUsuarios.setModel(modelo);
        jPanelAggUsuario.setVisible(true);    

    }//GEN-LAST:event_jButtonAggUsrActionPerformed

    private void jButtonConfAggUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfAggUsrActionPerformed
        String nmUsuario = jTextFieldNombreUsuario.getText();
        Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();
        Usuario nuevoUsuario = new Usuario();
        this.idMax = this.idMax+1;
        nuevoUsuario.setId(this.idMax);
        nuevoUsuario.setUsuario(nmUsuario);
        System.out.println("---->" + nuevoUsuario.getId());
        int idRelacion = 0;
        while(usuario!=null){
            if(usuario.getValor().getUsuario().equals(jListUsuarios.getSelectedValue())){
                idRelacion = usuario.getValor().getId();
                break;
            }
            usuario = usuario.getSiguiente();
        }

        Arista relacion = new Arista(nuevoUsuario.getId(),idRelacion,(Integer)jSpinnerAnios.getValue());

        Main.repo.getAristaList().agregarAlFinal(relacion);
        Main.repo.getUsuariosList().agregarAlFinal(nuevoUsuario);
        JOptionPane.showMessageDialog(this, "Usuario agregado correctamente");
        usuario = Main.repo.getUsuariosList().getPrimero();
        modelo = new DefaultListModel();
        while(usuario!=null){
            System.out.println(usuario.getValor().getUsuario());
            modelo.addElement(usuario.getValor().getUsuario());
            usuario=usuario.getSiguiente();
        }
        jListUsuarios.setModel(modelo);

//        usuario = Main.repo.getUsuariosList().getPrimero();
//        while(usuario!=null){
//            System.out.println(usuario.getValor().getUsuario());
//            usuario=usuario.getSiguiente();
//        }
    }//GEN-LAST:event_jButtonConfAggUsrActionPerformed

    private void jTextFieldNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioFocusLost
        if(jTextFieldNombreUsuario.getText()!=null ){
            if (!jTextFieldNombreUsuario.getText().isBlank() || !jTextFieldNombreUsuario.getText().isEmpty()){
                if(jListUsuarios.getSelectedValue()!=null && (Integer)jSpinnerAnios.getValue() != 0){
                    jButtonConfAggUsr.setEnabled(true);
                }else{
                            jButtonConfAggUsr.setEnabled(false);
                        }                
            }else{
                        jButtonConfAggUsr.setEnabled(false);
                    }
        }else{
                    jButtonConfAggUsr.setEnabled(false);
                }

    }//GEN-LAST:event_jTextFieldNombreUsuarioFocusLost

    private void jListUsuariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListUsuariosFocusLost
        if(jTextFieldNombreUsuario.getText()!=null ){
                    if (!jTextFieldNombreUsuario.getText().isBlank() || !jTextFieldNombreUsuario.getText().isEmpty()){
                        if(jListUsuarios.getSelectedValue()!=null && (Integer)jSpinnerAnios.getValue() != 0){
                            jButtonConfAggUsr.setEnabled(true);
                        }else{
                            jButtonConfAggUsr.setEnabled(false);
                        }                
            }else{
                        jButtonConfAggUsr.setEnabled(false);
                    }
        }else{
                    jButtonConfAggUsr.setEnabled(false);
                }       // TODO add your handling code here:
    }//GEN-LAST:event_jListUsuariosFocusLost

    private void jSpinnerAniosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinnerAniosFocusLost
        
    }//GEN-LAST:event_jSpinnerAniosFocusLost

    private void jSpinnerAniosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAniosStateChanged
                if(jTextFieldNombreUsuario.getText()!=null ){
                    if (!jTextFieldNombreUsuario.getText().isBlank() || !jTextFieldNombreUsuario.getText().isEmpty()){
                        if(jListUsuarios.getSelectedValue()!=null && (Integer)jSpinnerAnios.getValue() != 0){
                            jButtonConfAggUsr.setEnabled(true);
                        }else{
                            jButtonConfAggUsr.setEnabled(false);
                        }                
            }else{
                        jButtonConfAggUsr.setEnabled(false);
                    }
        }else{
                    jButtonConfAggUsr.setEnabled(false);
                }
    }//GEN-LAST:event_jSpinnerAniosStateChanged

    private void jButtonAggRelacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAggRelacActionPerformed
        // TODO add your handling code here:
        jButtonAggRelac.setEnabled(false);
        jButtonAggUsr.setEnabled(false);
        jButtonDelUsr.setEnabled(false);
        if(modelo==null){
            Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();
            modelo = new DefaultListModel();
            this.idMax = 0;
            while(usuario!=null){
                System.out.println(usuario.getValor().getUsuario());
                modelo.addElement(usuario.getValor().getUsuario());
                if(usuario.getValor().getId()>this.idMax)this.idMax=usuario.getValor().getId();
                usuario=usuario.getSiguiente();
            }
        }
        
        jListRelacion1.setModel(modelo);
        jListRelacion2.setModel(modelo);
        jPanelAggRelac.setVisible(true);
    }//GEN-LAST:event_jButtonAggRelacActionPerformed

    private void jButtonCerrarAggUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarAggUsrActionPerformed
        // TODO add your handling code here:
        jPanelAggUsuario.setVisible(false);
        jButtonAggRelac.setEnabled(true);
        jButtonAggUsr.setEnabled(true);
        jButtonDelUsr.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarAggUsrActionPerformed

    private void jButtonCerrarAggRelacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarAggRelacActionPerformed
        // TODO add your handling code here:
        jPanelAggRelac.setVisible(false);
        jButtonAggRelac.setEnabled(true);
        jButtonAggUsr.setEnabled(true);
        jButtonDelUsr.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarAggRelacActionPerformed

    private void jButtonConfAggRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfAggRelActionPerformed
        // TODO add your handling code here:
        Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();

        int idRelacionUsu1 = 0;
        int idRelacionUsu2 = 0;
        while(usuario!=null){
            if(usuario.getValor().getUsuario().equals(jListRelacion1.getSelectedValue())){
                idRelacionUsu1 = usuario.getValor().getId();
            }else if (usuario.getValor().getUsuario().equals(jListRelacion2.getSelectedValue())){
                idRelacionUsu2 = usuario.getValor().getId();
            }
            usuario = usuario.getSiguiente();
        }
        
        Arista relacion = new Arista(idRelacionUsu1,idRelacionUsu2,(Integer)jSpinnerAniosRel.getValue());

        Main.repo.getAristaList().agregarAlFinal(relacion);
        JOptionPane.showMessageDialog(this, "Relacion creada");
//        Nodo<Arista>arista = Main.repo.getAristaList().getPrimero();
//        while(arista!=null){
//            System.out.println("Origen-> "+arista.getValor().getOrigen()+ "; Destino-> "+arista.getValor().getDestino()+ ";Anios-> "+arista.getValor().getYears());
//            arista=arista.getSiguiente();
//        }
    }//GEN-LAST:event_jButtonConfAggRelActionPerformed

    private void jListRelacion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListRelacion1FocusLost
        // TODO add your handling code here:

        if(jListRelacion1.getSelectedValue()!=null && jListRelacion2.getSelectedValue()!=null && (Integer)jSpinnerAniosRel.getValue() != 0){
                            jButtonConfAggRel.setEnabled(true);
        }else{
            jButtonConfAggRel.setEnabled(false);
        } 
        
    }//GEN-LAST:event_jListRelacion1FocusLost

    private void jListRelacion2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListRelacion2FocusLost
        // TODO add your handling code here:
        if(jListRelacion1.getSelectedValue()!=null && jListRelacion2.getSelectedValue()!=null && (Integer)jSpinnerAniosRel.getValue() != 0){
                            jButtonConfAggRel.setEnabled(true);
        }else{
            jButtonConfAggRel.setEnabled(false);
        } 
    }//GEN-LAST:event_jListRelacion2FocusLost

    private void jSpinnerAniosRelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAniosRelStateChanged
        // TODO add your handling code here:
        if(jListRelacion1.getSelectedValue()!=null && jListRelacion2.getSelectedValue()!=null && (Integer)jSpinnerAniosRel.getValue() != 0){
                            jButtonConfAggRel.setEnabled(true);
        }else{
            jButtonConfAggRel.setEnabled(false);
        } 
    }//GEN-LAST:event_jSpinnerAniosRelStateChanged

    private void jButtonDelUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelUsrActionPerformed
//        // TODO add your handling code 
    }//GEN-LAST:event_jButtonDelUsrActionPerformed

    private void jButtonConfDelUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfDelUsrActionPerformed
        // TODO add your handling code here:
        
        Nodo<Usuario> usuario = Main.repo.getUsuariosList().getPrimero();

        int idRelacionUsu = 0;
        while(usuario!=null){
            if(usuario.getValor().getUsuario().equals(jListDelUsr.getSelectedValue())){
                idRelacionUsu = usuario.getValor().getId();
                if(usuario.getAnterior()!=null)usuario.getAnterior().setSiguiente(usuario.getSiguiente());
                if(usuario.getSiguiente()!=null)usuario.getSiguiente().setAnterior(usuario.getAnterior());
                break;
            }
            usuario = usuario.getSiguiente();
        }
        
        Nodo<Arista> relacion = Main.repo.getUsuariosList().getPrimero();

        while(relacion!=null){
            if(relacion.getValor().getDestino()== idRelacionUsu || relacion.getValor().getOrigen()== idRelacionUsu){
                if(relacion.getAnterior()!=null)relacion.getAnterior().setSiguiente(relacion.getSiguiente());
                if(relacion.getSiguiente()!=null)relacion.getSiguiente().setAnterior(relacion.getAnterior());
                break;
            }
            relacion = relacion.getSiguiente();
        }
        
        JOptionPane.showMessageDialog(this, "Usuario y sus relaciones eliminadas");
        Nodo<Arista>arista = Main.repo.getAristaList().getPrimero();
        while(arista!=null){
            System.out.println("Origen-> "+arista.getValor().getOrigen()+ "; Destino-> "+arista.getValor().getDestino()+ ";Anios-> "+arista.getValor().getYears());
            arista=arista.getSiguiente();
        }
        
        usuario = Main.repo.getUsuariosList().getPrimero();
        while(usuario!=null){
            System.out.println(usuario.getValor().getUsuario());
            usuario=usuario.getSiguiente();
        }
        
    }//GEN-LAST:event_jButtonConfDelUsrActionPerformed

    private void jButtonCerrarEliUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarEliUsrActionPerformed
//         TODO add your handling code here:
        jPanelDelUsr.setVisible(false);
        jButtonAggRelac.setEnabled(true);
        jButtonAggUsr.setEnabled(true);
        jButtonDelUsr.setEnabled(true);
    }//GEN-LAST:event_jButtonCerrarEliUsrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarRepo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarRepo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarRepo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarRepo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarRepo2 dialog = new ActualizarRepo2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private int idMax;
    private DefaultListModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAggRelac;
    private javax.swing.JButton jButtonAggUsr;
    private javax.swing.JButton jButtonCerrarAggRelac;
    private javax.swing.JButton jButtonCerrarAggUsr;
    private javax.swing.JButton jButtonCerrarEliUsr;
    private javax.swing.JButton jButtonConfAggRel;
    private javax.swing.JButton jButtonConfAggUsr;
    private javax.swing.JButton jButtonConfDelUsr;
    private javax.swing.JButton jButtonDelUsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListDelUsr;
    private javax.swing.JList<String> jListRelacion1;
    private javax.swing.JList<String> jListRelacion2;
    private javax.swing.JList<String> jListUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAggRelac;
    private javax.swing.JPanel jPanelAggUsuario;
    private javax.swing.JPanel jPanelDelUsr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerAnios;
    private javax.swing.JSpinner jSpinnerAniosRel;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
